In [1]:
import numpy as np

## 1D array

In [2]:
a=np.array([10,20,30,50,60,0])
a

array([10, 20, 30, 50, 60,  0])

## Attributes of arrays
#### dtype  ,   ndim   ,   size   ,   shape

In [3]:
a.dtype

dtype('int32')

In [4]:
#number of dimension of array
a.ndim

1

In [5]:
a.shape

(6,)

In [6]:
a.size

6

In [7]:
#indexing
a[0]

10

In [8]:
a[2]

30

## Multi dimensional array

In [9]:
a_2d=np.array([[10,20,30],[23,55,15]])
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [10]:
a_2d.dtype

dtype('int32')

In [11]:
a_2d.shape

(2, 3)

In [12]:
a_2d.size

6

In [13]:
a_2d.ndim

2

In [14]:
a_2d[0]

array([10, 20, 30])

### Another type of multi dimensional arrays

In [15]:
array_type2=np.array([[[1,2,3,4]]])
array_type2

array([[[1, 2, 3, 4]]])

In [16]:
array_type2.shape

(1, 1, 4)

In [17]:
array_type2.ndim

3

### Indexing First element of first array

In [18]:
a_2d[0][0]

10

In [19]:
#second element of second array
a_2d[1][1]

55

### Let's change its data type into float

In [20]:
a_2d=np.array([[10,20,30],[23,55,15]],dtype=float)
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

## Filling arrays

In [21]:
a_full=np.full((3,5,4),7)
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [22]:
a_full.ndim

3

## zeros and ones

In [23]:
a_zeros=np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:

b=np.ones((2,2,4))
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])